(()=>{
const KEY='skygates-v020-state',JKEY='skygates-v020-journal',ACHKEY='skygates-v020-achievements';let deferredInstall=null,audio=null,timer=null;
const defaults={tab:'today',place:'Melbourne',unit:'C',zodiacMode:'12',sign:'current',sound:'off',volume:.25,profile:{name:'',birthDate:'',guide:'Luna',experience:'balanced',favouritePlanet:'Moon',setupDone:false,homeCards:{rain:true,clothes:true,outside:true,moon:true,stars:true,number:true}},alerts:{horoscope:false,moon:false,sky:false,rain:false},notifyTime:'07:00',quality:'standard',redMode:false,reduceMotion:false,cinema:false};const state=Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'),{data:null,loading:false});state.profile=Object.assign({},defaults.profile,state.profile||{});state.alerts=Object.assign({},defaults.alerts,state.alerts||{});
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=0)=>Number.isFinite(+n)?(+n).toFixed(d):'—';const save=()=>localStorage.setItem(KEY,JSON.stringify({...state,data:undefined,loading:undefined}));
const signs12=[['Aries','♈','03-21','04-19'],['Taurus','♉','04-20','05-20'],['Gemini','♊','05-21','06-20'],['Cancer','♋','06-21','07-22'],['Leo','♌','07-23','08-22'],['Virgo','♍','08-23','09-22'],['Libra','♎','09-23','10-22'],['Scorpio','♏','10-23','11-21'],['Sagittarius','♐','11-22','12-21'],['Capricorn','♑','12-22','01-19'],['Aquarius','♒','01-20','02-18'],['Pisces','♓','02-19','03-20']];const signs13=[['Capricorn','♑','01-19','02-15'],['Aquarius','♒','02-16','03-11'],['Pisces','♓','03-12','04-18'],['Aries','♈','04-19','05-13'],['Taurus','♉','05-14','06-19'],['Gemini','♊','06-20','07-20'],['Cancer','♋','07-21','08-09'],['Leo','♌','08-10','09-15'],['Virgo','♍','09-16','10-30'],['Libra','♎','10-31','11-22'],['Scorpio','♏','11-23','11-28'],['Ophiuchus','⛎','11-29','12-17'],['Sagittarius','♐','12-18','01-18']];

const RETRO_GUIDE=[
{name:'Mercury',symbol:'☿',windows:[['2026-06-29','2026-07-23'],['2026-10-24','2026-11-13'],['2027-02-09','2027-03-03']],theme:'communication, edits and review'},
{name:'Venus',symbol:'♀',windows:[['2026-12-20','2027-01-31']],theme:'relationships, value and taste'},
{name:'Mars',symbol:'♂',windows:[['2027-01-10','2027-03-01']],theme:'energy, timing and motivation'},
{name:'Jupiter',symbol:'♃',windows:[['2026-11-11','2027-03-11']],theme:'growth, beliefs and long-range plans'},
{name:'Saturn',symbol:'♄',windows:[['2026-07-13','2026-11-28']],theme:'structure, accountability and patience'},
{name:'Uranus',symbol:'♅',windows:[['2026-09-06','2027-01-31']],theme:'change, freedom and experimentation'},
{name:'Neptune',symbol:'♆',windows:[['2026-07-07','2026-12-13']],theme:'dreams, uncertainty and intuition'},
{name:'Pluto',symbol:'♇',windows:[['2026-05-04','2026-10-14']],theme:'power, transformation and deep change'}
];
function retrogradeStatus(d=new Date()){const day=d.toISOString().slice(0,10);return RETRO_GUIDE.map(p=>{const active=p.windows.find(w=>day>=w[0]&&day<=w[1]);if(active){const days=Math.max(0,Math.ceil((new Date(active[1]+'T23:59:59Z')-d)/86400000));return{...p,status:'Retrograde',active,days}}const next=p.windows.find(w=>day<w[0]);return{...p,status:'Direct',next}})}
function retrogradePanel(){const rows=retrogradeStatus().map(p=>`<div class="zodiac ${p.status==='Retrograde'?'active':''}"><h4>${p.symbol} ${p.name}</h4><p>${p.status}</p><small>${p.status==='Retrograde'?`${p.active[0]} → ${p.active[1]} · ${p.days} days remaining`:(p.next?`Next guide window ${p.next[0]} → ${p.next[1]}`:'No future local window loaded')} · ${p.theme}</small></div>`).join('');return`<h3 style="margin-top:18px">Retrograde guide</h3><p><small>Planet status windows are shown for reflective use. Astronomy and astrology remain labelled separately.</small></p><div class="zodiac-grid">${rows}</div>`}

const wtxt=c=>({0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Cloudy',45:'Fog',48:'Icy fog',51:'Drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',80:'Showers',81:'Showers',82:'Heavy showers',95:'Thunderstorm',96:'Storm with hail',99:'Severe storm'}[c]||'Changing weather'),wicon=c=>c>=95?'⛈':c>=80?'🌧':c>=61?'🌦':c>=45?'🌫':c===0?'☀':'⛅';const t=c=>state.unit==='F'?c*9/5+32:c,tu=()=>`°${state.unit}`,wind=v=>state.unit==='F'?v*.621371:v,wu=()=>state.unit==='F'?'mph':'km/h';
function moon(d=new Date()){const syn=29.530588853,known=Date.UTC(2000,0,6,18,14),days=(d-known)/86400000,p=((days/syn)%1+1)%1,illum=(1-Math.cos(2*Math.PI*p))/2*100,age=p*syn;let name=p<.03||p>=.97?'New Moon':p<.22?'Waxing Crescent':p<.28?'First Quarter':p<.47?'Waxing Gibbous':p<.53?'Full Moon':p<.72?'Waning Gibbous':p<.78?'Last Quarter':'Waning Crescent';return{p,illum,age,name,wax:p<.5,toFull:((.5-p+1)%1)*syn,toNew:((1-p)%1)*syn}}

function birthMoon(){if(!state.profile.birthDate)return null;return moon(new Date(state.profile.birthDate+'T12:00:00'))}
function gematria(text){const letters=String(text||'').toUpperCase().replace(/[^A-Z]/g,'').split('');const parts=letters.map(ch=>[ch,ch.charCodeAt(0)-64]);const total=parts.reduce((a,x)=>a+x[1],0);let root=total;while(root>9)root=String(root).split('').reduce((a,n)=>a+Number(n),0);const titles={1:'Pathfinder',2:'Peacemaker',3:'Storyteller',4:'Builder',5:'Explorer',6:'Helper',7:'Seeker',8:'Achiever',9:'Humanitarian'};return{parts,total,root,title:titles[root]||'Mystery'}}
function personalGuide(){return state.profile.guide||'Luna'}
function greeting(){const h=new Date().getHours(),g=h<12?'Good morning':h<18?'Good afternoon':'Good evening';return state.profile.name?`${g}, ${state.profile.name}`:`${g}, sky explorer`}
function birthdayCountdown(){if(!state.profile.birthDate)return null;const now=new Date(),b=new Date(state.profile.birthDate+'T12:00:00'),next=new Date(now.getFullYear(),b.getMonth(),b.getDate());if(next<new Date(now.getFullYear(),now.getMonth(),now.getDate()))next.setFullYear(now.getFullYear()+1);return Math.ceil((next-new Date(now.getFullYear(),now.getMonth(),now.getDate()))/86400000)}
function achievements(){const a=JSON.parse(localStorage.getItem(ACHKEY)||'{}');a.firstForecast=!!state.data;a.profile=!!state.profile.name;a.birthMoon=!!state.profile.birthDate;a.journal=(JSON.parse(localStorage.getItem(JKEY)||'[]').length>0);a.ophiuchus=state.zodiacMode==='13';localStorage.setItem(ACHKEY,JSON.stringify(a));return a}
function onboarding(){return`<div class="onboard-backdrop"><section class="onboard-card panel"><span class="eyebrow">WELCOME TO YOUR PERSONALISED UNIVERSE</span><h2>What should Skygates call you?</h2><p>Your details stay on this device. You can change them later.</p><div class="onboard-grid"><label>Your name<input id="onName" maxlength="40" placeholder="Type your name"></label><label>Your birthday<input id="onBirth" type="date"></label><label>Your sky guide<select id="onGuide"><option>Luna</option><option>Nova</option><option>Atlas</option><option>Aurora</option></select></label><label>Your main view<select id="onExperience"><option value="balanced">Weather and space equally</option><option value="weather">Mostly weather</option><option value="sky">Mostly Moon and stars</option></select></label></div><div class="row"><button class="btn primary" id="finishSetup">Open my Skygate</button><button class="btn" id="skipSetup">Skip for now</button></div><small>Gematria and astrology are optional symbolic activities for fun. Weather and astronomy remain factual sections.</small></section></div>`}
function profilePanel(){const bm=birthMoon(),g=gematria(state.profile.name),days=birthdayCountdown(),a=achievements();return`<section class="panel section profile-vault"><span class="eyebrow">MY SKYGATE PROFILE</span><h2>${esc(state.profile.name||'Sky Explorer')} · ${esc(personalGuide())}'s companion</h2><div class="profile-grid"><div class="profile-orb"><span>${birthSign()==='Ophiuchus'?'⛎':signs12.find(x=>x[0]===birthSign())?.[1]||'✦'}</span><b>${birthSign()}</b><small>Your Sun sign</small></div><div class="profile-orb"><span>🌙</span><b>${bm?bm.name:'Add birthday'}</b><small>${bm?`${Math.round(bm.illum)}% lit when you were born`:'See your birth Moon'}</small></div><div class="profile-orb"><span>🔢</span><b>${g.total||'—'} → ${g.root||'—'}</b><small>${g.title} · symbolic name number</small></div><div class="profile-orb"><span>🎂</span><b>${days===null?'—':days===0?'Today!':days+' days'}</b><small>Birthday countdown</small></div></div><h3>Achievements</h3><div class="badge-row">${[['firstForecast','First Forecast','🌦'],['profile','My Skygate','✨'],['birthMoon','Birth Moon','🌙'],['journal','Sky Writer','📓'],['ophiuchus','Ophiuchus Explorer','⛎']].map(x=>`<span class="achievement ${a[x[0]]?'earned':''}">${x[2]} ${x[1]}</span>`).join('')}</div></section>`}
function gematriaPanel(){const g=gematria(state.profile.name);return`<section class="panel section gematria"><span class="eyebrow">NAME & NUMBER PLAY · SYMBOLIC FUN</span><h2>${esc(state.profile.name||'Your name')}: ${g.total||'—'}</h2><p>${g.total?`Your digital root is <b>${g.root}</b>, nicknamed <b>The ${g.title}</b>. This is a playful reflection, not science or a prediction.`:'Add your name to see the calculation.'}</p>${g.parts.length?`<div class="letter-values">${g.parts.map(x=>`<span><b>${x[0]}</b><small>${x[1]}</small></span>`).join('')}</div><p class="equation">${g.parts.map(x=>x[1]).join(' + ')} = <b>${g.total}</b> → ${g.root}</p>`:''}<details class="number-details"><summary>How this works</summary><div class="details-body">This optional English alphabet method uses A=1, B=2, through Z=26. Spaces and punctuation are ignored. Traditional Hebrew gematria is a different historical system and is not being claimed here.</div></details></section>`}
function customHomeSettings(){const h=state.profile.homeCards||defaults.profile.homeCards;return`<div class="custom-home"><h3>Choose my Today cards</h3>${[['rain','Will it rain?'],['clothes','What should I wear?'],['outside','Can I play outside?'],['moon','What shape is the Moon?'],['stars','Can I see stars?'],['number','My symbolic number']].map(x=>`<label><input type="checkbox" data-home-card="${x[0]}" ${h[x[0]]?'checked':''}> ${x[1]}</label>`).join('')}</div>`}
function moonSvg(m){const r=92,cx=110,cy=110,k=Math.cos(2*Math.PI*m.p),sx=m.p<.5?cx+k*88:cx-k*88;return`<svg class="moon-svg" viewBox="0 0 220 220"><defs><radialGradient id="ml" cx="35%" cy="30%"><stop offset="0" stop-color="#fff"/><stop offset=".55" stop-color="#ded8ca"/><stop offset="1" stop-color="#938a7e"/></radialGradient><clipPath id="mc"><circle cx="110" cy="110" r="92"/></clipPath></defs><circle cx="110" cy="110" r="92" fill="url(#ml)"/><g opacity=".18"><circle cx="82" cy="78" r="13"/><circle cx="144" cy="91" r="16"/><circle cx="98" cy="132" r="19"/><circle cx="140" cy="145" r="9"/></g><circle cx="${sx}" cy="110" r="92" fill="#050814" clip-path="url(#mc)"/><circle cx="110" cy="110" r="92" fill="none" stroke="rgba(255,255,255,.24)"/></svg>`}
function signSet(){return state.zodiacMode==='13'?signs13:signs12}function inRange(md,a,b){return a<=b?md>=a&&md<=b:md>=a||md<=b}function currentSign(d=new Date()){const md=String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');return signSet().find(x=>inRange(md,x[2],x[3]))||signSet()[0]}function birthSign(){if(!state.profile.birthDate)return currentSign()[0];const d=new Date(state.profile.birthDate+'T12:00:00');const md=String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');return signs12.find(x=>inRange(md,x[2],x[3]))?.[0]||currentSign()[0]}
async function weather(place){const g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(place)}&count=1&language=en&format=json`).then(r=>r.json());if(!g.results?.length)throw Error('Location not found');const x=g.results[0],u=new URL('https://api.open-meteo.com/v1/forecast');u.search=new URLSearchParams({latitude:x.latitude,longitude:x.longitude,timezone:'auto',forecast_days:'8',current:'temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,wind_gusts_10m,surface_pressure,cloud_cover,is_day',hourly:'temperature_2m,precipitation_probability,weather_code,wind_speed_10m,wind_gusts_10m,cloud_cover,visibility,uv_index',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset'});const d=await fetch(u).then(r=>r.json());d.label=x.name+(x.admin1?', '+x.admin1:'');return d}
function startIdx(){const h=state.data?.hourly?.time||[];let i=h.findIndex(x=>new Date(x)>=new Date());return i<0?0:i}function skyScore(i){const d=state.data;if(!d)return 0;const cloud=d.hourly.cloud_cover[i]||0,rain=d.hourly.precipitation_probability[i]||0,vis=Math.min(100,(d.hourly.visibility[i]||0)/200),m=moon(new Date(d.hourly.time[i])),moonPenalty=m.illum*.18;return Math.max(0,Math.min(100,Math.round(100-cloud*.65-rain*.3-moonPenalty+vis*.25)))}function bestSky(){if(!state.data)return null;const s=startIdx(),h=state.data.hourly;let best=null;for(let i=s;i<Math.min(s+24,h.time.length);i++){const hour=new Date(h.time[i]).getHours();if(hour<18&&hour>5)continue;const sc=skyScore(i);if(!best||sc>best.score)best={i,score:sc}}return best}
function reading(){const m=moon(),sg=birthSign(),active=currentSign()[0],name=state.profile.name?state.profile.name+', ':'';return`${name}${sg} energy meets the ${m.name.toLowerCase()} under a ${active} season. Use the weather side for practical timing and the sky side for reflection. Move steadily, notice patterns, and keep one important decision simple today.`}
function header(){return`<div class="top"><div class="brand"><img src="./trinity-knot.svg"><div><span class="eyebrow">50% WEATHER · 50% ASTRONOMY</span><h1>SKYGATES</h1><small>${esc(state.place)} · ${new Date().toLocaleString([], {weekday:'short',hour:'numeric',minute:'2-digit'})}</small></div></div><div class="top-actions"><button class="btn" id="unit">${tu()}</button><button class="btn" id="refresh">↻ Refresh</button><button class="btn primary" id="install">Install app</button></div></div>`}
function nav(){const tabs=[['today','◐','Today'],['weather','☀','Weather'],['sky','✦','Sky'],['horoscope','♈','Horoscope'],['journal','✎','Journal'],['more','•••','More']];return`<div class="tabs">${tabs.map(x=>`<button class="btn ${state.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]} ${x[2]}</button>`).join('')}</div>`}
function home(){const d=state.data,m=moon(),c=d?.current,b=bestSky(),s=b?.score||0,cls=s>=70?'good':s>=40?'mid':'';return`<div class="split"><section class="panel hero-half"><span class="eyebrow">WEATHER REALITY</span><h2>${c?wicon(c.weather_code):'☁'} ${c?fmt(t(c.temperature_2m),1)+tu():'Loading'}</h2><p>${c?wtxt(c.weather_code):'Fetching live weather'} for ${d?esc(d.label):esc(state.place)}. Practical decisions stay grounded in real forecast data.</p><div class="metric-row"><div class="metric"><small>Feels like</small><b>${c?fmt(t(c.apparent_temperature),1)+tu():'—'}</b></div><div class="metric"><small>Rain next hour</small><b>${d?(d.hourly.precipitation_probability[startIdx()]||0)+'%':'—'}</b></div><div class="metric"><small>Wind</small><b>${c?fmt(wind(c.wind_speed_10m))+ ' '+wu():'—'}</b></div></div></section><section class="panel hero-half"><span class="eyebrow">ASTRONOMY & NIGHT SKY</span><div class="moon-wrap moon-orbit">${moonSvg(m)}<h2>${m.name}</h2><p>${fmt(m.illum,1)}% illuminated · ${m.wax?'Waxing':'Waning'} · age ${fmt(m.age,1)} days</p></div><div class="metric-row"><div class="metric"><small>Tonight score</small><b class="${cls}">${s}/100</b></div><div class="metric"><small>Best time</small><b>${b?new Date(d.hourly.time[b.i]).toLocaleTimeString([],{hour:'numeric'}):'—'}</b></div><div class="metric"><small>Season</small><b>${currentSign()[1]} ${currentSign()[0]}</b></div></div></section></div><div class="subgrid"><section class="panel section">${timeline()}</section><section class="panel section"><h3>Today’s Skygate reading</h3><p>${esc(reading())}</p><div class="row"><button class="btn" data-tab="horoscope">Open horoscope</button><button class="btn" id="playMood">Play ambience</button></div></section></div>`}
function timeline(){if(!state.data)return'<h3>24-hour weather / sky timeline</h3><p>Loading…</p>';const s=startIdx(),h=state.data.hourly,rows=h.time.slice(s,s+12).map((x,k)=>{const i=s+k,sc=skyScore(i);return`<div class="time-row"><small>${new Date(x).toLocaleTimeString([],{hour:'numeric'})}</small><span>${wicon(h.weather_code[i])}</span><b>${fmt(t(h.temperature_2m[i]))}${tu()}</b><span>${h.cloud_cover[i]||0}% cloud · ${h.precipitation_probability[i]||0}% rain</span><strong>${sc}/100 sky</strong></div>`}).join('');return`<h3>24-hour weather / sky timeline</h3><p>Weather and viewing quality together.</p><div class="timeline">${rows}</div>`}
function weatherTab(){if(!state.data)return'<section class="panel section">Loading weather…</section>';const d=state.data,c=d.current,s=startIdx();return`<section class="panel section"><h3>Professional weather command</h3><p>${esc(d.label)} · ${wtxt(c.weather_code)}</p><div class="card-grid"><div class="card"><small>Temperature</small><h2>${fmt(t(c.temperature_2m),1)}${tu()}</h2><p>Feels ${fmt(t(c.apparent_temperature),1)}${tu()}</p></div><div class="card"><small>Wind and gusts</small><h2>${fmt(wind(c.wind_speed_10m))} ${wu()}</h2><p>Gusts ${fmt(wind(c.wind_gusts_10m))} ${wu()}</p></div><div class="card"><small>Atmosphere</small><h2>${fmt(c.surface_pressure)} hPa</h2><p>${c.relative_humidity_2m}% humidity</p></div></div>${timeline()}</section>`}
function skyTab(){const m=moon(),b=bestSky(),d=state.data;const upcoming=Array.from({length:8},(_,i)=>{const x=new Date(Date.now()+i*86400000),mm=moon(x);return`<div class="sky-card"><h4>${x.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}</h4><p>${mm.name}</p><small>${fmt(mm.illum,0)}% illuminated</small></div>`}).join('');return`<section class="panel section"><h3>Tonight’s sky</h3><p>Viewing quality blends clouds, rain, visibility and moon brightness.</p><div class="split"><div class="moon-wrap moon-orbit">${moonSvg(m)}<h2>${fmt(m.illum,1)}%</h2><p>${m.name} · ${m.wax?'Waxing':'Waning'}</p></div><div><div class="score ${b&&b.score>=70?'good':'mid'}">${b?b.score:'—'}/100</div><h3>${b?'Best around '+new Date(d.hourly.time[b.i]).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Waiting for weather'}</h3><p>${b&&b.score>=70?'Very good viewing potential.':b&&b.score>=40?'Mixed conditions; watch cloud breaks.':'Poor viewing conditions tonight.'}</p><div class="card-grid"><div class="card"><small>Moon age</small><b>${fmt(m.age,1)} days</b></div><div class="card"><small>Next full</small><b>${fmt(m.toFull,1)} days</b></div><div class="card"><small>Next new</small><b>${fmt(m.toNew,1)} days</b></div></div></div></div><h3 style="margin-top:18px">Lunar calendar</h3><div class="card-grid">${upcoming}</div></section>`}
function horoscopeTab(){const sg=birthSign(),m=moon(),cards=signSet().map(x=>`<div class="zodiac ${x[0]===currentSign()[0]?'active':''}"><h4>${x[1]} ${x[0]}</h4><small>${x[2]} → ${x[3]}</small></div>`).join('');return`<section class="panel section"><h3>Daily horoscope</h3><p>${esc(reading())}</p><div class="card-grid"><div class="card"><small>Your sign</small><h2>${sg}</h2></div><div class="card"><small>Moon influence</small><h2>${m.name}</h2></div><div class="card"><small>System</small><h2>${state.zodiacMode==='13'?'13 + Ophiuchus':'Traditional 12'}</h2></div></div><h3 style="margin-top:18px">Zodiac wheel</h3><div class="zodiac-grid">${cards}</div>${retrogradePanel()}</section>${gematriaPanel()}`}
function journalTab(){const items=JSON.parse(localStorage.getItem(JKEY)||'[]');return`<section class="panel section"><h3>Observation journal</h3><p>Save what you saw with today’s weather and moon automatically attached.</p><div class="journal-form"><input id="jTitle" placeholder="Observation title"><input id="jRating" type="number" min="1" max="5" placeholder="Rating 1–5"><textarea id="jNotes" placeholder="What did you see or notice?"></textarea><button class="btn primary" id="saveJournal">Save observation</button></div><div class="timeline">${items.length?items.map(x=>`<div class="journal-item"><h4>${esc(x.title)}</h4><p>${esc(x.notes)}</p><small>${esc(x.date)} · ${esc(x.weather)} · ${esc(x.moon)} · ${x.rating}/5</small></div>`).join(''):'<p>No observations saved yet.</p>'}</div></section>`}
function moreTab(){return`<section class="panel section"><h3>App, alerts and ambience</h3><div class="settings-grid"><label class="switch">Location<input id="place" value="${esc(state.place)}"></label><label class="switch">Zodiac system<select id="zMode"><option value="12">12 signs</option><option value="13">13 signs + Ophiuchus</option></select></label><label class="switch">Name<input id="pName" value="${esc(state.profile.name)}"></label><label class="switch">Birth date<input id="pBirth" type="date" value="${esc(state.profile.birthDate)}"></label><label class="switch">Daily horoscope alert<input id="aH" type="checkbox" ${state.alerts.horoscope?'checked':''}></label><label class="switch">Moon phase alert<input id="aM" type="checkbox" ${state.alerts.moon?'checked':''}></label><label class="switch">Clear-sky alert<input id="aS" type="checkbox" ${state.alerts.sky?'checked':''}></label><label class="switch">Rain alert<input id="aR" type="checkbox" ${state.alerts.rain?'checked':''}></label><label class="switch">Reminder time<input id="nTime" type="time" value="${state.notifyTime}"></label><label class="switch">Ambience<select id="sound"><option value="off">Off</option><option value="temple">Temple night</option><option value="rain">Soft rain</option><option value="space">Deep space</option></select></label><label class="switch">Graphics quality<select id="quality"><option value="low">Battery saver</option><option value="standard">Standard</option><option value="ultra">Ultra immersive</option></select></label><label class="switch">Red-light observing<input id="redMode" type="checkbox" ${state.redMode?'checked':''}></label><label class="switch">Reduce motion<input id="reduceMotion" type="checkbox" ${state.reduceMotion?'checked':''}></label></div><div class="row" style="margin-top:14px"><button class="btn primary" id="saveSettings">Save settings</button><button class="btn" id="enableNotify">Enable notifications</button><button class="btn" id="install2">Install app</button><button class="btn" id="stopSound">Stop ambience</button><button class="btn" id="cinemaMode">Full-screen immersive</button></div><p><small>Alerts are local while the app/browser is active. Guaranteed closed-app push requires a future secure push service.</small></p></section>`}

/* V018 simple, fun explanation layer */
function rainStory(p){p=Number(p||0);return p>=70?{icon:'☔',title:'Take an umbrella',text:'Rain is likely.'}:p>=35?{icon:'🌦',title:'Keep an umbrella nearby',text:'A shower might pop up.'}:{icon:'🧢',title:'Probably dry',text:'Rain is not very likely.'}}
function windStory(v){v=Number(v||0);return v>=45?{icon:'💨',title:'Very windy',text:'Hold onto hats and loose things.'}:v>=25?{icon:'🍃',title:'A breezy day',text:'You will feel the wind outside.'}:{icon:'🪁',title:'Light wind',text:'The air should feel fairly calm.'}}
function tempStory(c){const x=Number(c||0);return x>=32?{icon:'🥵',title:'Very hot',text:'Drink water and stay in the shade.'}:x>=24?{icon:'😎',title:'Warm',text:'Light clothes should feel good.'}:x>=16?{icon:'🙂',title:'Mild',text:'A light layer may be handy.'}:x>=8?{icon:'🧥',title:'Cool',text:'Take a jumper or jacket.'}:{icon:'🥶',title:'Cold',text:'Wear warm layers.'}}
function skyStory(score){score=Number(score||0);return score>=75?{icon:'🌟',title:'Great star-watching night',text:'The sky should be clear enough to see plenty.'}:score>=50?{icon:'🔭',title:'Worth a look',text:'Some clouds may come and go.'}:score>=25?{icon:'☁️',title:'A tricky sky tonight',text:'You may only see stars through cloud gaps.'}:{icon:'🏠',title:'Not a good sky night',text:'Clouds or rain will probably hide most things.'}}
function moonStory(m){if(m.illum<8)return'The Moon is almost dark. This helps faint stars stand out.';if(m.illum>92)return'The Moon is almost completely bright and round.';if(m.wax)return'The bright part is growing a little more each night.';return'The bright part is shrinking a little more each night.'}
function simpleReading(){const m=moon(),name=state.profile.name?state.profile.name+', ':'';return`${name}today is a good day to stay curious, be kind, and finish one small job. The ${m.name.toLowerCase()} reminds us that change happens a little at a time.`}
function explainCard(icon,title,text,extra=''){return`<article class="answer-card"><div class="answer-icon">${icon}</div><div><h3>${title}</h3><p>${text}</p>${extra}</div></article>`}
function numberDetails(html){return`<details class="number-details"><summary>Show the numbers</summary><div class="details-body">${html}</div></details>`}
function header(){return`<div class="top"><div class="brand"><img src="./trinity-knot.svg"><div><span class="eyebrow">WEATHER + SPACE, MADE SIMPLE</span><h1>SKYGATES</h1><small>${esc(state.place)} · ${new Date().toLocaleString([], {weekday:'long',hour:'numeric',minute:'2-digit'})}</small></div></div><div class="top-actions"><button class="btn" id="unit">Use ${state.unit==='C'?'°F':'°C'}</button><button class="btn" id="refresh">↻ Update</button><button class="btn primary" id="install">📲 Install</button></div></div>`}
function nav(){const tabs=[['today','🏠','Today'],['weather','🌦','Weather'],['sky','🌙','Moon & Stars'],['horoscope','✨','My Reading'],['journal','📓','My Sky Book'],['more','⚙','More']];return`<div class="tabs friendly-tabs">${tabs.map(x=>`<button class="btn ${state.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]} ${x[2]}</button>`).join('')}</div>`}
function home(){const d=state.data,m=moon(),c=d?.current,i=startIdx(),rain=d?.hourly?.precipitation_probability?.[i]||0,b=bestSky(),score=b?.score||0,rs=rainStory(rain),ws=windStory(c?.wind_speed_10m),ts=tempStory(c?.temperature_2m),ss=skyStory(score);return`<section class="welcome panel"><span class="eyebrow">${greeting().toUpperCase()}</span><h2>${c?`${wicon(c.weather_code)} ${wtxt(c.weather_code)}`:'Finding your weather…'}</h2><p class="big-answer">${c?`${ts.title}. ${rs.title}.`:'One moment while Skygates looks outside.'}</p></section><div class="simple-grid">${explainCard(ts.icon,ts.title,ts.text)}${explainCard(rs.icon,rs.title,rs.text)}${explainCard(ws.icon,ws.title,ws.text)}${explainCard(ss.icon,ss.title,ss.text)}</div><div class="split"><section class="panel hero-half friendly-hero"><span class="eyebrow">OUTSIDE TODAY</span><div class="friendly-weather-icon">${c?wicon(c.weather_code):'☁️'}</div><h2>${c?Math.round(t(c.temperature_2m))+tu():'—'}</h2><p>${c?`It feels like ${Math.round(t(c.apparent_temperature))}${tu()}. ${ts.text}`:'Loading live weather.'}</p>${numberDetails(`<b>Rain:</b> ${rain}%<br><b>Wind:</b> ${c?Math.round(wind(c.wind_speed_10m))+' '+wu():'—'}<br><b>Humidity:</b> ${c?.relative_humidity_2m??'—'}%`)}</section><section class="panel hero-half friendly-hero"><span class="eyebrow">MOON & STARS TONIGHT</span><div class="moon-wrap moon-orbit">${moonSvg(m)}</div><h2>${m.name}</h2><p class="big-answer">${moonStory(m)}</p><div class="kid-score ${score>=75?'great':score>=50?'okay':'poor'}"><span>${ss.icon}</span><b>${ss.title}</b></div>${numberDetails(`<b>Moon lit:</b> ${Math.round(m.illum)}%<br><b>Sky score:</b> ${score}/100<br><b>Best time:</b> ${b&&d?new Date(d.hourly.time[b.i]).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Waiting for weather'}`)}</section></div><section class="panel section story-panel"><span class="story-badge">✨ TODAY'S LITTLE MESSAGE</span><h3>${esc(simpleReading())}</h3><div class="row"><button class="btn primary" data-tab="weather">Plan my day</button><button class="btn" data-tab="sky">See tonight's sky</button><button class="btn" id="playMood">♫ Play gentle sounds</button></div></section>${state.profile.name?profilePanel():''}`}
function timeline(){if(!state.data)return'<h3>What happens next?</h3><p>Loading…</p>';const s=startIdx(),h=state.data.hourly,rows=h.time.slice(s,s+8).map((x,k)=>{const i=s+k,r=rainStory(h.precipitation_probability[i]),sc=skyStory(skyScore(i));return`<div class="story-row"><time>${new Date(x).toLocaleTimeString([],{hour:'numeric'})}</time><span class="story-weather">${wicon(h.weather_code[i])}</span><div><b>${Math.round(t(h.temperature_2m[i]))}${tu()} · ${r.title}</b><small>${new Date(x).getHours()>=18||new Date(x).getHours()<6?sc.title:wtxt(h.weather_code[i])}</small></div></div>`}).join('');return`<h3>What happens next?</h3><p>Swipe through the next few hours in plain English.</p><div class="story-timeline">${rows}</div>${numberDetails('The detailed forecast still uses live temperature, rain, cloud and visibility data.')}`}
function weatherTab(){if(!state.data)return'<section class="panel section">Looking outside…</section>';const d=state.data,c=d.current,i=startIdx(),rain=d.hourly.precipitation_probability[i]||0,rs=rainStory(rain),ws=windStory(c.wind_speed_10m),ts=tempStory(c.temperature_2m);return`<section class="panel section"><span class="eyebrow">WEATHER MADE EASY</span><h2>What should I know today?</h2><div class="simple-grid">${explainCard(ts.icon,'What should I wear?',`${ts.title}. ${ts.text}`)}${explainCard(rs.icon,'Will it rain?',`${rs.title}. ${rs.text}`)}${explainCard(ws.icon,'Is it windy?',`${ws.title}. ${ws.text}`)}${explainCard('🏃','Can I play outside?',rain>=70||c.weather_code>=95?'Indoor plans may be better for now.':'Yes — check again before heading out.')}</div>${timeline()}${numberDetails(`<b>Temperature:</b> ${fmt(t(c.temperature_2m),1)}${tu()}<br><b>Feels like:</b> ${fmt(t(c.apparent_temperature),1)}${tu()}<br><b>Rain chance:</b> ${rain}%<br><b>Wind:</b> ${fmt(wind(c.wind_speed_10m))} ${wu()}<br><b>Pressure:</b> ${fmt(c.surface_pressure)} hPa<br><b>Humidity:</b> ${c.relative_humidity_2m}%`)}</section>`}
function skyTab(){const m=moon(),b=bestSky(),d=state.data,score=b?.score||0,ss=skyStory(score);const days=Array.from({length:8},(_,i)=>{const x=new Date(Date.now()+i*86400000),mm=moon(x);return`<div class="moon-day"><b>${x.toLocaleDateString([],{weekday:'short'})}</b><span>${mm.illum<8?'🌑':mm.illum<35?(mm.wax?'🌒':'🌘'):mm.illum<65?(mm.wax?'🌓':'🌗'):mm.illum<92?(mm.wax?'🌔':'🌖'):'🌕'}</span><small>${mm.name}</small></div>`}).join('');return`<section class="panel section"><span class="eyebrow">MOON & STARS MADE EASY</span><h2>What can I see tonight?</h2><div class="sky-answer"><div class="moon-wrap moon-orbit">${moonSvg(m)}</div><div>${explainCard(ss.icon,ss.title,ss.text)}${explainCard('🌙',m.name,moonStory(m))}${explainCard('🕘','Best time to look',b&&d?`Try around ${new Date(d.hourly.time[b.i]).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}.`:'We are still checking the clouds.')}</div></div><h3>The Moon this week</h3><div class="moon-week">${days}</div>${numberDetails(`<b>Moon illuminated:</b> ${fmt(m.illum,1)}%<br><b>Moon age:</b> ${fmt(m.age,1)} days<br><b>Next full Moon:</b> about ${fmt(m.toFull,1)} days<br><b>Next new Moon:</b> about ${fmt(m.toNew,1)} days<br><b>Sky score:</b> ${score}/100`)}<details class="number-details"><summary>What does “waxing” or “waning” mean?</summary><div class="details-body"><b>Waxing</b> means the bright part is growing. <b>Waning</b> means it is shrinking. The Moon itself is not changing shape — sunlight makes it look that way.</div></details></section>`}
function retrogradePanel(){const active=retrogradeStatus().filter(p=>p.status==='Retrograde');return`<div class="retro-simple"><h3>Why do some planets look backwards?</h3><p>Sometimes Earth and another planet pass each other in space. From here, that planet can <em>look</em> like it moves backwards for a while. It is only an optical effect.</p>${active.length?`<p><b>Right now:</b> ${active.map(p=>p.symbol+' '+p.name).join(', ')} appear retrograde in this guide.</p>`:'<p><b>Right now:</b> none of the guide windows are active.</p>'}${numberDetails(retrogradeStatus().map(p=>`${p.symbol} <b>${p.name}:</b> ${p.status}`).join('<br>'))}</div>`}
function horoscopeTab(){const sg=birthSign(),cur=currentSign();return`<section class="panel section"><span class="eyebrow">A FUN DAILY REFLECTION</span><h2>${state.profile.name?esc(state.profile.name)+"'s":'Your'} little Skygate message</h2><div class="story-card"><div class="answer-icon">${cur[1]}</div><h3>${esc(simpleReading())}</h3><p>Horoscopes are imaginative reflections for fun. They do not predict what must happen.</p></div><div class="simple-grid">${explainCard('💛','Kindness challenge','Do one helpful thing without being asked.')}${explainCard('🧠','Curiosity challenge','Ask one good question today.')}${explainCard('✅','Small-win challenge','Finish one easy job before starting another.')}${explainCard('♈',`Your sign: ${sg}`,'Your birth date chooses your traditional Sun sign.')}</div>${retrogradePanel()}${numberDetails(`<b>Current zodiac season:</b> ${cur[1]} ${cur[0]}<br><b>Selected system:</b> ${state.zodiacMode==='13'?'13 signs including Ophiuchus':'Traditional 12 signs'}`)}</section>`}
function journalTab(){const items=JSON.parse(localStorage.getItem(JKEY)||'[]');return`<section class="panel section"><span class="eyebrow">MY SKY BOOK</span><h2>What did you notice?</h2><p>Draw it on paper, take a photo, or write a few words here.</p><div class="journal-form"><input id="jTitle" placeholder="What did you see? e.g. A bright Moon"><select id="jRating"><option value="5">Amazing!</option><option value="4">Really good</option><option value="3" selected>Interesting</option><option value="2">Hard to see</option><option value="1">Could not see much</option></select><textarea id="jNotes" placeholder="Tell your future self what happened…"></textarea><button class="btn primary" id="saveJournal">📓 Save in my Sky Book</button></div><div class="timeline">${items.length?items.map(x=>`<div class="journal-item"><h4>🌟 ${esc(x.title)}</h4><p>${esc(x.notes)}</p><small>${esc(x.date)} · ${esc(x.weather)} · ${esc(x.moon)}</small></div>`).join(''):'<div class="empty-story">Your Sky Book is empty. Tonight could be your first entry!</div>'}</div></section>`}
function moreTab(){return`<section class="panel section"><span class="eyebrow">GROWN-UP SETTINGS & FUN EXTRAS</span><h2>Make Skygates yours</h2><div class="settings-grid"><label class="switch">My town<input id="place" value="${esc(state.place)}"></label><label class="switch">Zodiac choice<select id="zMode"><option value="12">Traditional 12 signs</option><option value="13">13 signs with Ophiuchus</option></select></label><label class="switch">My name<input id="pName" value="${esc(state.profile.name)}"></label><label class="switch">My birthday<input id="pBirth" type="date" value="${esc(state.profile.birthDate)}"></label><label class="switch">Daily fun message<input id="aH" type="checkbox" ${state.alerts.horoscope?'checked':''}></label><label class="switch">Moon reminder<input id="aM" type="checkbox" ${state.alerts.moon?'checked':''}></label><label class="switch">Good star night alert<input id="aS" type="checkbox" ${state.alerts.sky?'checked':''}></label><label class="switch">Rain reminder<input id="aR" type="checkbox" ${state.alerts.rain?'checked':''}></label><label class="switch">Reminder time<input id="nTime" type="time" value="${state.notifyTime}"></label><label class="switch">Gentle sounds<select id="sound"><option value="off">Off</option><option value="temple">Moon chimes</option><option value="rain">Soft rain</option><option value="space">Space hum</option></select></label><label class="switch">Graphics<select id="quality"><option value="low">Save battery</option><option value="standard">Normal</option><option value="ultra">Full magic</option></select></label><label class="switch">Red telescope screen<input id="redMode" type="checkbox" ${state.redMode?'checked':''}></label><label class="switch">Less movement<input id="reduceMotion" type="checkbox" ${state.reduceMotion?'checked':''}></label><label class="switch">My sky guide<select id="pGuide"><option>Luna</option><option>Nova</option><option>Atlas</option><option>Aurora</option></select></label><label class="switch">My main view<select id="pExperience"><option value="balanced">Weather and space equally</option><option value="weather">Mostly weather</option><option value="sky">Mostly Moon and stars</option></select></label></div>${customHomeSettings()}<div class="row" style="margin-top:14px"><button class="btn primary" id="saveSettings">Save my choices</button><button class="btn" id="enableNotify">Allow reminders</button><button class="btn" id="install2">📲 Put app on my phone</button><button class="btn" id="stopSound">Stop sounds</button><button class="btn" id="cinemaMode">Big-screen mode</button></div><details class="number-details"><summary>Important grown-up information</summary><div class="details-body">Weather comes from live forecast data. Moon phases are calculated locally. Astrology is for reflection and fun. Reminders work locally while the app or browser is active; guaranteed closed-app push needs a future secure service.</div></details></section>`}

function body(){return state.tab==='today'?home():state.tab==='weather'?weatherTab():state.tab==='sky'?skyTab():state.tab==='horoscope'?horoscopeTab():state.tab==='journal'?journalTab():moreTab()}
function render(){document.querySelector('#app').innerHTML=`<div class="shell">${header()}${nav()}<div id="view">${body()}</div></div>${!state.profile.setupDone?onboarding():''}<nav class="dock">${[['today','🏠','Today'],['weather','🌦','Weather'],['sky','🌙','Sky'],['horoscope','✨','Reading'],['more','⚙','More']].map(x=>`<button class="${state.tab===x[0]?'active':''}" data-tab="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav>`;bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;save();render()});$('#unit').onclick=()=>{state.unit=state.unit==='C'?'F':'C';save();render()};$('#refresh').onclick=load;$('#install').onclick=install;$('#install2')&&($('#install2').onclick=install);$('#playMood')&&($('#playMood').onclick=()=>playSound(state.sound==='off'?'temple':state.sound));$('#saveJournal')&&($('#saveJournal').onclick=saveJournal);$('#saveSettings')&&($('#saveSettings').onclick=saveSettings);$('#enableNotify')&&($('#enableNotify').onclick=enableNotify);$('#stopSound')&&($('#stopSound').onclick=stopSound);if($('#zMode'))$('#zMode').value=state.zodiacMode;if($('#sound'))$('#sound').value=state.sound;if($('#quality'))$('#quality').value=state.quality;if($('#pGuide'))$('#pGuide').value=state.profile.guide||'Luna';if($('#pExperience'))$('#pExperience').value=state.profile.experience||'balanced';$('#finishSetup')&&($('#finishSetup').onclick=finishSetup);$('#skipSetup')&&($('#skipSetup').onclick=()=>{state.profile.setupDone=true;save();render()});applyImmersive();$('#cinemaMode')&&($('#cinemaMode').onclick=toggleCinema);setupTilt()}
function finishSetup(){state.profile.name=$('#onName').value.trim();state.profile.birthDate=$('#onBirth').value;state.profile.guide=$('#onGuide').value;state.profile.experience=$('#onExperience').value;state.profile.setupDone=true;save();render()}
function saveJournal(){const arr=JSON.parse(localStorage.getItem(JKEY)||'[]'),m=moon(),c=state.data?.current;arr.unshift({title:$('#jTitle').value||'Sky observation',notes:$('#jNotes').value||'',rating:$('#jRating').value||3,date:new Date().toLocaleString(),weather:c?wtxt(c.weather_code):'Unknown',moon:m.name});localStorage.setItem(JKEY,JSON.stringify(arr.slice(0,100)));render()}
function saveSettings(){state.place=$('#place').value||'Melbourne';state.zodiacMode=$('#zMode').value;state.profile.name=$('#pName').value;state.profile.birthDate=$('#pBirth').value;state.alerts={horoscope:$('#aH').checked,moon:$('#aM').checked,sky:$('#aS').checked,rain:$('#aR').checked};state.notifyTime=$('#nTime').value;state.sound=$('#sound').value;state.quality=$('#quality').value;state.redMode=$('#redMode').checked;state.reduceMotion=$('#reduceMotion').checked;state.profile.guide=$('#pGuide')?.value||state.profile.guide;state.profile.experience=$('#pExperience')?.value||state.profile.experience;state.profile.setupDone=true;state.profile.homeCards=state.profile.homeCards||{};document.querySelectorAll('[data-home-card]').forEach(x=>state.profile.homeCards[x.dataset.homeCard]=x.checked);save();applyImmersive();playSound(state.sound);load()}
async function enableNotify(){if(!('Notification'in window))return alert('Notifications are not supported on this device.');const p=await Notification.requestPermission();if(p==='granted')new Notification('SKYGATES alerts enabled',{body:'Your selected local alerts are ready.',icon:'./icon-192.png'})}
async function install(){if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;return}if(/iphone|ipad|ipod/i.test(navigator.userAgent))alert('On iPhone/iPad: open in Safari, tap Share, then Add to Home Screen.');else alert('Use your browser menu and choose Install app or Add to Home screen.')}
function stopSound(){if(timer)clearInterval(timer);timer=null;if(audio){audio.close();audio=null}}
function tone(freq,dur=.7,type='sine',gain=.035){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,audio.currentTime);g.gain.linearRampToValueAtTime(gain*state.volume,audio.currentTime+.08);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function playSound(mode){stopSound();if(mode==='off')return;audio=new (window.AudioContext||window.webkitAudioContext)();const seq=mode==='rain'?[180,165,210,150]:mode==='space'?[110,165,220,330]:[261.6,392,523.2,392];let i=0;tone(seq[0],1.6,'sine',.05);timer=setInterval(()=>tone(seq[i++%seq.length],1.8,mode==='rain'?'triangle':'sine',.05),1800)}
function applyImmersive(){document.body.classList.remove('quality-low','quality-standard','quality-ultra','red-mode','weather-rain','weather-storm','weather-clear','weather-night');document.body.classList.add('quality-'+(state.quality||'standard'));if(state.redMode)document.body.classList.add('red-mode');if(state.reduceMotion)document.documentElement.style.setProperty('--motion','.01');else document.documentElement.style.removeProperty('--motion');const c=state.data?.current;if(c){if(c.weather_code>=95)document.body.classList.add('weather-storm');else if(c.weather_code>=51)document.body.classList.add('weather-rain');else if(c.weather_code<=1)document.body.classList.add('weather-clear');if(c.is_day===0)document.body.classList.add('weather-night')}}
function toggleCinema(){const p=document.querySelector('#view .panel');if(!p)return;p.classList.toggle('cinema');state.cinema=p.classList.contains('cinema');save()}
function setupTilt(){if(state.reduceMotion||state.quality==='low'||matchMedia('(pointer:coarse)').matches)return;document.querySelectorAll('.panel').forEach(el=>{el.onpointermove=e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`rotateX(${-y*2.4}deg) rotateY(${x*2.4}deg) translateZ(4px)`};el.onpointerleave=()=>el.style.transform=''})}
function startCosmos(){const c=document.getElementById('cosmosCanvas');if(!c)return;const x=c.getContext('2d');let stars=[];function size(){const d=Math.min(devicePixelRatio||1,2);c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(d,0,0,d,0,0);stars=Array.from({length:state.quality==='ultra'?220:state.quality==='low'?55:120},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.6+.2,a:Math.random()*.7+.2,s:Math.random()*.08+.015}))}function draw(t){x.clearRect(0,0,innerWidth,innerHeight);for(const q of stars){q.y+=q.s*(state.reduceMotion?0:1);if(q.y>innerHeight)q.y=0;const tw=.55+.45*Math.sin(t*.0015+q.x);x.beginPath();x.fillStyle=`rgba(220,235,255,${q.a*tw})`;x.arc(q.x,q.y,q.r,0,Math.PI*2);x.fill()}requestAnimationFrame(draw)}addEventListener('resize',size);size();requestAnimationFrame(draw)}

function startDigitalWorld(){
 const canvas=document.getElementById('digitalWorld');if(!canvas)return;const g=canvas.getContext('2d',{alpha:true});let W=0,H=0,D=1,clouds=[],drops=[],stars=[],dust=[],last=0;
 const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 function rebuild(){D=Math.min(devicePixelRatio||1,state.quality==='ultra'?2:1.5);W=innerWidth;H=innerHeight;canvas.width=Math.max(1,Math.floor(W*D));canvas.height=Math.max(1,Math.floor(H*D));canvas.style.width=W+'px';canvas.style.height=H+'px';g.setTransform(D,0,0,D,0,0);
  const q=state.quality==='ultra'?1.6:state.quality==='low'?.55:1;
  clouds=Array.from({length:Math.round(10*q)},()=>({x:rand(-W*.2,W),y:rand(H*.02,H*.55),w:rand(W*.18,W*.46),h:rand(60,170),v:rand(.04,.16),a:rand(.035,.13)}));
  drops=Array.from({length:Math.round(260*q)},()=>({x:rand(0,W),y:rand(-H,H),l:rand(10,34),v:rand(7,18),a:rand(.08,.34)}));
  stars=Array.from({length:Math.round(360*q)},()=>({x:rand(0,W),y:rand(0,H*.78),r:rand(.25,1.7),a:rand(.12,.9),z:rand(.2,1)}));
  dust=Array.from({length:Math.round(80*q)},()=>({x:rand(0,W),y:rand(0,H),r:rand(.4,2.2),a:rand(.02,.14),v:rand(.02,.12)}));
 }
 function weatherNow(){const c=state.data?.current||{};return{code:+c.weather_code||0,cloud:clamp(+c.cloud_cover||25,0,100),wind:clamp(+c.wind_speed_10m||5,0,90),day:c.is_day!==0,temp:+c.temperature_2m||15}}
 function sky(t,w){const night=!w.day;let top,bottom;if(night){top='#020411';bottom='#0c1731'}else if(w.code>=95){top='#111827';bottom='#354254'}else if(w.code>=51){top='#243247';bottom='#607185'}else{top='#1373b8';bottom='#83c7ed'}const grad=g.createLinearGradient(0,0,0,H);grad.addColorStop(0,top);grad.addColorStop(.65,bottom);grad.addColorStop(1,'#07101d');g.fillStyle=grad;g.fillRect(0,0,W,H);
  const sunX=W*.18,sunY=H*.17;if(w.day&&w.code<80){const rg=g.createRadialGradient(sunX,sunY,2,sunX,sunY,Math.min(W,H)*.24);rg.addColorStop(0,'rgba(255,248,194,.95)');rg.addColorStop(.08,'rgba(255,220,120,.5)');rg.addColorStop(1,'rgba(255,184,80,0)');g.fillStyle=rg;g.fillRect(0,0,W,H)}
  if(night){for(const s of stars){const tw=.55+.45*Math.sin(t*.0015+s.x);g.beginPath();g.fillStyle=`rgba(220,235,255,${s.a*tw})`;g.arc(s.x,s.y,s.r,0,Math.PI*2);g.fill()}}
 }
 function drawMoon(t,w){const m=moon(),r=Math.min(W,H)*(state.quality==='ultra'?.115:.095),cx=W*(W<760?.72:.73),cy=H*(W<760?.24:.22);g.save();g.translate(cx,cy);const halo=g.createRadialGradient(0,0,r*.6,0,0,r*2.5);halo.addColorStop(0,'rgba(220,235,255,.24)');halo.addColorStop(1,'rgba(150,190,255,0)');g.fillStyle=halo;g.fillRect(-r*2.6,-r*2.6,r*5.2,r*5.2);g.beginPath();g.arc(0,0,r,0,Math.PI*2);const mg=g.createRadialGradient(-r*.35,-r*.38,r*.05,0,0,r);mg.addColorStop(0,'#fffdf2');mg.addColorStop(.55,'#d8d2c4');mg.addColorStop(1,'#7e786f');g.fillStyle=mg;g.fill();g.save();g.clip();for(let i=0;i<34;i++){const a=i*2.399,rr=r*Math.sqrt((i+.4)/34)*.82,x=Math.cos(a)*rr,y=Math.sin(a)*rr*.93,cr=r*(.025+(i%7)*.008);g.beginPath();g.fillStyle=`rgba(55,58,62,${.05+(i%5)*.018})`;g.arc(x,y,cr,0,Math.PI*2);g.fill()}
  const phase=Math.cos(2*Math.PI*m.p),offset=(m.p<.5?1:-1)*phase*r;g.beginPath();g.arc(offset,0,r*1.01,0,Math.PI*2);g.fillStyle='rgba(1,3,12,.93)';g.fill();g.restore();g.strokeStyle='rgba(255,255,255,.28)';g.lineWidth=1;g.stroke();g.restore()}
 function drawClouds(w){const density=.25+w.cloud/100*.9;for(const c of clouds){c.x+=c.v*(1+w.wind/18)*(state.reduceMotion?0:1);if(c.x-c.w>W)c.x=-c.w;c.a=.02+density*.1;const rg=g.createRadialGradient(c.x,c.y,4,c.x,c.y,c.w*.55);rg.addColorStop(0,`rgba(225,238,248,${c.a})`);rg.addColorStop(.5,`rgba(130,157,183,${c.a*.65})`);rg.addColorStop(1,'rgba(80,100,120,0)');g.fillStyle=rg;g.save();g.scale(1,.42);g.fillRect(c.x-c.w,c.y/.42-c.h,c.w*2,c.h*2);g.restore()}}
 function drawRain(w){if(w.code<51)return;const strength=w.code>=95?1:w.code>=80?.82:.55;g.lineWidth=1;for(const d of drops){d.y+=d.v*strength*(state.reduceMotion?.15:1);d.x-=d.v*.16;if(d.y>H){d.y=rand(-160,-10);d.x=rand(0,W)}g.strokeStyle=`rgba(195,225,255,${d.a*strength})`;g.beginPath();g.moveTo(d.x,d.y);g.lineTo(d.x-4,d.y+d.l);g.stroke()}}
 function portal(t){const cx=W*.5,cy=H*.47,r=Math.min(W,H)*(W<760?.17:.22);g.save();g.translate(cx,cy);g.rotate(t*.00008*(state.reduceMotion?0:1));for(let i=0;i<3;i++){g.beginPath();g.setLineDash(i===1?[8,14]:[]);g.lineWidth=1.2;g.strokeStyle=i===0?'rgba(117,221,255,.18)':i===1?'rgba(200,145,255,.16)':'rgba(242,211,132,.1)';g.arc(0,0,r*(1-i*.19),0,Math.PI*2);g.stroke()}g.setLineDash([]);const glow=g.createRadialGradient(0,0,0,0,0,r);glow.addColorStop(0,'rgba(115,211,255,.06)');glow.addColorStop(.7,'rgba(178,114,255,.035)');glow.addColorStop(1,'rgba(0,0,0,0)');g.fillStyle=glow;g.beginPath();g.arc(0,0,r,0,Math.PI*2);g.fill();g.restore()}
 function frame(t){const w=weatherNow();document.body.classList.toggle('digital-day',w.day);document.body.classList.toggle('digital-night',!w.day);g.clearRect(0,0,W,H);sky(t,w);drawMoon(t,w);portal(t);drawClouds(w);drawRain(w);for(const d of dust){d.y-=d.v*(state.reduceMotion?0:1);if(d.y<0)d.y=H;g.fillStyle=`rgba(210,230,255,${d.a})`;g.fillRect(d.x,d.y,d.r,d.r)}last=t;requestAnimationFrame(frame)}
 addEventListener('resize',rebuild);rebuild();requestAnimationFrame(frame)
}

function checkAlerts(){if(Notification.permission!=='granted')return;const now=new Date(),hm=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0'),key=now.toISOString().slice(0,10),last=localStorage.getItem('skygates-v020-last-alert');if(state.alerts.horoscope&&hm===state.notifyTime&&last!==key){localStorage.setItem('skygates-v020-last-alert',key);new Notification('Your Skygate day is ready',{body:reading(),icon:'./icon-192.png'})}}
async function load(){if(state.loading)return;state.loading=true;render();try{state.data=await weather(state.place)}catch(e){alert(e.message)}finally{state.loading=false;render()}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.addEventListener('DOMContentLoaded',()=>{const q=new URLSearchParams(location.search).get('tab');if(q)state.tab=q;render();startCosmos();startDigitalWorld();load();setInterval(checkAlerts,30000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});

// V021 Living Sky: additive visual layer; no forecast, profile or storage semantics changed.
function startV021LivingSky(){
 if(document.querySelector('.v021-world'))return;
 const world=document.createElement('div');world.className='v021-world';world.setAttribute('aria-hidden','true');world.innerHTML='<div class="v021-aurora"></div><div class="v021-nebula"></div><div class="v021-horizon"></div><div class="v021-scan"></div>';
 const flash=document.createElement('div');flash.className='v021-flash';flash.setAttribute('aria-hidden','true');
 const pulse=document.createElement('div');pulse.className='v021-pulse';pulse.setAttribute('aria-live','polite');pulse.innerHTML='<i class="v021-pulse-dot"></i><strong>SKY PULSE</strong><span>connecting…</span>';
 document.body.append(world,flash,pulse);
 const pulseText=pulse.querySelector('span');
 function updatePulse(){const c=state.data?.current;if(!c){pulseText.textContent='reading the sky…';return}const condition=wtxt(c.weather_code);const phase=moon().name;const temp=Math.round(t(c.temperature_2m))+tu();pulseText.textContent=`${condition} · ${temp} · ${phase}`}
 updatePulse();setInterval(updatePulse,15000);
 let lastStorm=0;setInterval(()=>{const code=+(state.data?.current?.weather_code||0);if(code>=95&&!state.reduceMotion&&Date.now()-lastStorm>7000){lastStorm=Date.now();flash.classList.remove('on');void flash.offsetWidth;flash.classList.add('on')}},2200);
 document.addEventListener('pointerdown',e=>{if(state.reduceMotion||e.target.closest('input,textarea,select'))return;const r=document.createElement('i');r.className='v021-ripple';r.style.left=e.clientX+'px';r.style.top=e.clientY+'px';document.body.appendChild(r);setTimeout(()=>r.remove(),950)},{passive:true});
 const observer=new MutationObserver(()=>{const view=document.getElementById('view');if(!view)return;view.classList.remove('v021-enter');void view.offsetWidth;view.classList.add('v021-enter');updatePulse()});
 const app=document.getElementById('app');if(app)observer.observe(app,{childList:true,subtree:false});
 startV021Constellations();
}
function startV021Constellations(){
 const c=document.createElement('canvas');c.id='v021Constellations';c.setAttribute('aria-hidden','true');Object.assign(c.style,{position:'fixed',inset:'0',width:'100%',height:'100%',zIndex:'0',pointerEvents:'none',opacity:'.72'});document.body.appendChild(c);
 const g=c.getContext('2d');let W=0,H=0,D=1,stars=[],meteors=[];
 function resize(){D=Math.min(devicePixelRatio||1,1.6);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;g.setTransform(D,0,0,D,0,0);const count=state.quality==='ultra'?70:state.quality==='low'?18:42;stars=Array.from({length:count},()=>({x:Math.random()*W,y:Math.random()*H*.72,v:Math.random()*.06+.01,a:Math.random()*.45+.12,r:Math.random()*1.25+.25}))}
 function meteor(){if(state.reduceMotion||state.quality==='low'||meteors.length>2)return;meteors.push({x:Math.random()*W*.75,y:Math.random()*H*.35,v:8+Math.random()*8,l:70+Math.random()*100,a:.8})}
 setInterval(()=>{if(Math.random()>.48)meteor()},5200);
 function frame(t){g.clearRect(0,0,W,H);for(const s of stars){s.y+=s.v*(state.reduceMotion?0:1);if(s.y>H*.75)s.y=0;g.fillStyle=`rgba(215,239,255,${s.a*(.55+.45*Math.sin(t*.001+s.x))})`;g.beginPath();g.arc(s.x,s.y,s.r,0,Math.PI*2);g.fill()}for(let i=0;i<stars.length;i++){let best=null,bd=130;for(let j=i+1;j<stars.length;j++){const dx=stars[i].x-stars[j].x,dy=stars[i].y-stars[j].y,d=Math.hypot(dx,dy);if(d<bd){bd=d;best=stars[j]}}if(best&&bd<105){g.strokeStyle=`rgba(125,216,255,${(1-bd/105)*.11})`;g.lineWidth=.7;g.beginPath();g.moveTo(stars[i].x,stars[i].y);g.lineTo(best.x,best.y);g.stroke()}}meteors=meteors.filter(m=>m.a>.02&&m.x<W+200&&m.y<H);for(const m of meteors){m.x+=m.v;m.y+=m.v*.43;m.a*=.966;const grad=g.createLinearGradient(m.x,m.y,m.x-m.l,m.y-m.l*.43);grad.addColorStop(0,`rgba(255,255,255,${m.a})`);grad.addColorStop(.28,`rgba(128,230,255,${m.a*.65})`);grad.addColorStop(1,'rgba(100,160,255,0)');g.strokeStyle=grad;g.lineWidth=1.4;g.beginPath();g.moveTo(m.x,m.y);g.lineTo(m.x-m.l,m.y-m.l*.43);g.stroke()}requestAnimationFrame(frame)}
 addEventListener('resize',resize);resize();requestAnimationFrame(frame);
}
window.addEventListener('DOMContentLoaded',startV021LivingSky);

})();
