import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.min.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state={place:'Melbourne, Victoria',lat:-37.8136,lon:144.9631,data:null,motion:true,effects:true,quality:'Automatic'};
const canvas=$('#threeCanvas'), renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100);camera.position.set(0,0,8);
const ambient=new THREE.AmbientLight(0x7890a8,1.4);scene.add(ambient);const key=new THREE.DirectionalLight(0xffd59a,3);key.position.set(-4,4,4);scene.add(key);
const sun=new THREE.Mesh(new THREE.SphereGeometry(.42,32,32),new THREE.MeshBasicMaterial({color:0xffd36a}));scene.add(sun);const moon=new THREE.Mesh(new THREE.SphereGeometry(.32,32,32),new THREE.MeshStandardMaterial({color:0xe6edf7,roughness:.8,emissive:0x7080a0,emissiveIntensity:.6}));scene.add(moon);
const starGeo=new THREE.BufferGeometry(), starN=600, starPos=new Float32Array(starN*3);for(let i=0;i<starN;i++){starPos[i*3]=(Math.random()-.5)*20;starPos[i*3+1]=Math.random()*9-1;starPos[i*3+2]=-5-Math.random()*5}starGeo.setAttribute('position',new THREE.BufferAttribute(starPos,3));const stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xffffff,size:.025,transparent:true,opacity:0}));scene.add(stars);
const cloudGroup=new THREE.Group();scene.add(cloudGroup);for(let i=0;i<18;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.35+Math.random()*.6,16,12),new THREE.MeshLambertMaterial({color:0xcdd7e0,transparent:true,opacity:.12,depthWrite:false}));m.scale.set(2.5+Math.random()*3,.5+Math.random()*.7,1);m.position.set((Math.random()-.5)*12,1+Math.random()*4,-2-Math.random()*3);cloudGroup.add(m)}
const rainN=1600, rainPos=new Float32Array(rainN*3);for(let i=0;i<rainN;i++){rainPos[i*3]=(Math.random()-.5)*12;rainPos[i*3+1]=Math.random()*10-4;rainPos[i*3+2]=Math.random()*4-2}const rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPos,3));const rainPts=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:0xb9ddff,size:.025,transparent:true,opacity:0}));scene.add(rainPts);
const weatherCanvas=$('#weatherCanvas'),ctx=weatherCanvas.getContext('2d');let lightningTimer=0,storm=false,raining=false,rainStrength=0,cloudCover=0,windSpeed=0,isDay=true;
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();weatherCanvas.width=innerWidth*devicePixelRatio;weatherCanvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
let px=0,py=0;addEventListener('pointermove',e=>{px=(e.clientX/innerWidth-.5);py=(e.clientY/innerHeight-.5)});addEventListener('deviceorientation',e=>{if(e.gamma!=null){px=Math.max(-1,Math.min(1,e.gamma/35));py=Math.max(-1,Math.min(1,(e.beta-45)/45))}});
function wmo(code){if([0].includes(code))return['Clear','☀️'];if([1,2].includes(code))return['Partly cloudy','⛅'];if([3].includes(code))return['Cloudy','☁️'];if([45,48].includes(code))return['Foggy','🌫️'];if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(code))return['Rain','🌧️'];if([71,73,75,77,85,86].includes(code))return['Snow','🌨️'];if([95,96,99].includes(code))return['Thunderstorm','⛈️'];return['Changing','🌦️']}
function moonPhase(date=new Date()){const lp=2551443;const now=date.getTime()/1000;const newMoon=new Date('2001-01-24T13:00:00Z').getTime()/1000;let phase=((now-newMoon)%lp)/lp;if(phase<0)phase+=1;const names=['New Moon','Waxing Crescent','First Quarter','Waxing Gibbous','Full Moon','Waning Gibbous','Last Quarter','Waning Crescent'];const idx=Math.round(phase*8)%8;const illum=Math.round((1-Math.cos(phase*Math.PI*2))/2*100);return[names[idx],illum]}
async function geocode(name){const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?count=1&language=en&format=json&name='+encodeURIComponent(name));const j=await r.json();if(!j.results?.length)throw Error('Location not found');return j.results[0]}
async function loadWeather(){setState('CONNECTING');const u=`https://api.open-meteo.com/v1/forecast?latitude=${state.lat}&longitude=${state.lon}&current=temperature_2m,apparent_temperature,is_day,precipitation,rain,weather_code,cloud_cover,relative_humidity_2m,wind_speed_10m&hourly=temperature_2m,precipitation_probability,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset&timezone=auto&forecast_days=8`;try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('Weather request failed');state.data=await r.json();localStorage.setItem('v028weather',JSON.stringify({t:Date.now(),place:state.place,lat:state.lat,lon:state.lon,data:state.data}));render();setState('LIVE OPEN-METEO')}catch(e){const c=JSON.parse(localStorage.getItem('v028weather')||'null');if(c){state.data=c.data;state.place=c.place;state.lat=c.lat;state.lon=c.lon;render();setState('CACHED · '+new Date(c.t).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}))}else{setState('UPDATE FAILED');$('#condition').textContent='Live weather unavailable';}}}
function setState(s){$('#dataState').textContent=s;$('#updated').textContent=s.startsWith('LIVE')?'Updated '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):s}
function render(){const d=state.data,c=d.current,day=d.daily,h=d.hourly,[desc,glyph]=wmo(c.weather_code);$('#placeName').textContent=state.place;$('#temperature').textContent=Math.round(c.temperature_2m)+'°';$('#condition').textContent=desc;$('#feels').textContent='Feels like '+Math.round(c.apparent_temperature)+'°';$('#highLow').textContent='↑ '+Math.round(day.temperature_2m_max[0])+'°   ↓ '+Math.round(day.temperature_2m_min[0])+'°';$('#conditionGlyph').textContent=glyph;$('#rain').textContent=Math.round(h.precipitation_probability[new Date().getHours()]||0)+'%';$('#wind').textContent=Math.round(c.wind_speed_10m)+' km/h';$('#humidity').textContent=Math.round(c.relative_humidity_2m)+'%';isDay=!!c.is_day;storm=[95,96,99].includes(c.weather_code);raining=storm||[51,53,55,56,57,61,63,65,66,67,80,81,82].includes(c.weather_code)||c.rain>0;rainStrength=Math.min(1,(c.precipitation||0)/5+.25);cloudCover=c.cloud_cover/100;windSpeed=c.wind_speed_10m;applyScene();renderForecast();const [mp,il]=moonPhase();$('#moonPhase').textContent=mp;$('#moonLight').textContent=il+'%';$('#stargazing').textContent=cloudCover<.35&&!raining?'Good':cloudCover<.7?'Fair':'Poor';$('#skyStatus').textContent=`${desc}. The live scene is using ${Math.round(c.cloud_cover)}% cloud cover, ${Math.round(c.wind_speed_10m)} km/h wind and ${raining?'active rain effects':'dry conditions'}.`;}
function renderForecast(){const d=state.data,h=d.hourly,day=d.daily,now=new Date();let idx=h.time.findIndex(t=>new Date(t)>=now);if(idx<0)idx=0;const cards=[];for(let i=idx;i<Math.min(idx+8,h.time.length);i++){const [x,g]=wmo(h.weather_code[i]);cards.push(`<div><small>${new Date(h.time[i]).toLocaleTimeString([],{hour:'numeric'})}</small><b>${g}</b><span>${Math.round(h.temperature_2m[i])}°</span><small>💧${h.precipitation_probability[i]}%</small></div>`)}$('#hourStrip').innerHTML=cards.join('');const full=[];for(let i=idx;i<Math.min(idx+24,h.time.length);i++){const [x,g]=wmo(h.weather_code[i]);full.push(`<div><small>${new Date(h.time[i]).toLocaleTimeString([],{hour:'numeric'})}</small><b>${g}</b><span>${Math.round(h.temperature_2m[i])}°</span><small>${h.precipitation_probability[i]}% rain</small></div>`)}$('#hourGrid').innerHTML=full.join('');$('#weekGrid').innerHTML=day.time.slice(0,7).map((t,i)=>`<div><b>${new Date(t+'T12:00').toLocaleDateString([],{weekday:'long'})}</b><span>${wmo(day.weather_code[i])[1]}</span><span>${Math.round(day.temperature_2m_max[i])}° / ${Math.round(day.temperature_2m_min[i])}° · ${day.precipitation_probability_max[i]}%</span></div>`).join('')}
function applyScene(){document.body.dataset.weather=storm?'storm':raining?'rain':cloudCover>.72?'cloudy':isDay?'day':'night';const filters=isDay?`brightness(${1.02-cloudCover*.22}) saturate(${1.05-cloudCover*.15})`:`brightness(.48) saturate(.78) hue-rotate(8deg)`;$$('.layer').forEach(x=>x.style.filter=filters);stars.material.opacity=isDay?0:Math.max(.25,1-cloudCover);sun.visible=isDay;moon.visible=!isDay;sun.position.set(-3.7,2.6,-1);moon.position.set(3.4,2.8,-1);cloudGroup.children.forEach(x=>x.material.opacity=.04+cloudCover*.22);rainPts.material.opacity=state.effects&&raining?.65*rainStrength:0;ambient.intensity=isDay?1.25-cloudCover*.45:.38;key.intensity=isDay?3-cloudCover*1.8:.45;key.color.set(isDay?0xffd59a:0x90a8cf)}
let last=performance.now();function animate(t){requestAnimationFrame(animate);const dt=Math.min(.05,(t-last)/1000);last=t;if(state.motion){camera.position.x+=(px*.42-camera.position.x)*.04;camera.position.y+=(-py*.22-camera.position.y)*.04;$('.sky').style.transform=`scale(1.12) translate(${px*-7}px,${py*-4}px)`;$('.temple').style.transform=`scale(1.08) translate(${px*-13}px,${py*-7}px)`;$('.foreground').style.transform=`scale(1.06) translate(${px*-22}px,${py*-10}px)`}cloudGroup.position.x+=dt*(.03+windSpeed*.006);if(cloudGroup.position.x>4)cloudGroup.position.x=-4;const p=rainGeo.attributes.position.array;if(raining&&state.effects){for(let i=0;i<rainN;i++){p[i*3+1]-=dt*(5+rainStrength*8);p[i*3]+=dt*.5;if(p[i*3+1]<-4){p[i*3+1]=6;p[i*3]=(Math.random()-.5)*12}}rainGeo.attributes.position.needsUpdate=true}stars.rotation.y+=dt*.005;if(storm&&state.effects&&t-lightningTimer>2500+Math.random()*5500){lightningTimer=t;const f=$('#flash');f.style.opacity='.85';setTimeout(()=>f.style.opacity='0',80);setTimeout(()=>{f.style.opacity='.35';setTimeout(()=>f.style.opacity='0',60)},150)}renderer.render(scene,camera)}requestAnimationFrame(animate);
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.page))});$('#refresh').onclick=loadWeather;$('#motion').onchange=e=>state.motion=e.target.checked;$('#effects').onchange=e=>{state.effects=e.target.checked;applyScene()};$('#quality').onclick=()=>{state.quality=state.quality==='Automatic'?'Battery saver':'Automatic';$('#quality').textContent='Quality: '+state.quality;renderer.setPixelRatio(state.quality==='Battery saver'?1:Math.min(devicePixelRatio,1.6))};$('#locate').onclick=async()=>{const q=prompt('Enter a suburb or city');if(!q)return;try{const g=await geocode(q);state.place=[g.name,g.admin1].filter(Boolean).join(', ');state.lat=g.latitude;state.lon=g.longitude;loadWeather()}catch(e){alert(e.message)}};setInterval(()=>$('#clock').textContent='Local time '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),1000);loadWeather().finally(()=>{setTimeout(()=>{$('#boot').style.opacity='0';setTimeout(()=>$('#boot').remove(),650)},350)});
