import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.184.0/build/three.module.min.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={lat:-37.8136,lon:144.9631,place:'Melbourne, Victoria',weather:null,motion:true,effects:true,quality:'auto'};
const codes={0:'Clear sky',1:'Mainly clear',2:'Partly cloudy',3:'Cloudy',45:'Fog',48:'Fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm',99:'Severe thunderstorm'};
const icons=c=>c===0?'☀️':c<=2?'🌤️':c===3?'☁️':c<=48?'🌫️':c>=95?'⛈️':c>=71&&c<=75?'🌨️':'🌧️';
const fmtTime=iso=>new Date(iso).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
const fmtDay=iso=>new Date(iso).toLocaleDateString([], {weekday:'short'});
let scene,camera,renderer,clock,world,clouds=[],rain,stars,sun,moon,hemi,sunLight,moonLight,flash,palms=[],ocean,pathMaterial,stormNext=0;
function mat(color,rough=.7,metal=.05){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})}
function addBox(parent,size,pos,material,rot=[0,0,0]){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),material);m.position.set(...pos);m.rotation.set(...rot);m.castShadow=m.receiveShadow=true;parent.add(m);return m}
function makeGate(x){const g=new THREE.Group();g.position.x=x;const stone=mat(0x252728,.93,.02);for(let i=0;i<7;i++){const y=.45+i*.48, w=1.35-i*.10;addBox(g,[w,.44,.72],[0,y,0],stone,[0,0,x<0?-.045:.045])}for(let i=0;i<5;i++){const y=3.7+i*.42, w=.72-i*.08;addBox(g,[w,.35,.58],[x<0?-.18:.18,y,0],stone,[0,0,x<0?-.14:.14])}for(let i=0;i<6;i++){const orb=new THREE.Mesh(new THREE.SphereGeometry(.10,8,6),mat(0x303334));orb.position.set((Math.random()-.5)*.8,.5+i*.62,.38);g.add(orb)}world.add(g);}
function makeTemple(){const t=new THREE.Group();const dark=mat(0x252728),gold=mat(0xb87a25,.55,.18);addBox(t,[2.8,.45,1.9],[0,.35,-3.3],dark);addBox(t,[2.2,.85,1.5],[0,1,-3.3],dark);for(let i=0;i<4;i++){const roof=addBox(t,[3-i*.48,.18,1.9-i*.18],[0,1.48+i*.42,-3.3],dark,[0,0,0]);roof.scale.y=.55}const lamp=new THREE.PointLight(0xffa83d,3,8);lamp.position.set(0,1.3,-2.7);t.add(lamp);addBox(t,[.18,.6,.18],[0,1.35,-2.65],gold);world.add(t)}
function makePalm(x,z,s=.8){const p=new THREE.Group();const trunk=mat(0x5b3822,.9);for(let i=0;i<7;i++)addBox(p,[.12,.6,.12],[0,i*.5,0],trunk,[0,0,(i-3)*.015]);const leafMat=new THREE.MeshStandardMaterial({color:0x1f5b39,roughness:.8,side:THREE.DoubleSide});for(let i=0;i<9;i++){const leaf=new THREE.Mesh(new THREE.PlaneGeometry(1.5,.22,4,1),leafMat);leaf.position.y=3.4;leaf.rotation.set((Math.random()-.5)*.45,i/9*Math.PI*2,(Math.random()-.5)*.25);leaf.translateX(.63);p.add(leaf)}p.position.set(x,0,z);p.scale.setScalar(s);world.add(p);palms.push(p)}
function makeCloud(){const g=new THREE.Group();const m=new THREE.MeshLambertMaterial({color:0xd9e4ed,transparent:true,opacity:.34,depthWrite:false});for(let i=0;i<7;i++){const q=new THREE.Mesh(new THREE.SphereGeometry(.55+Math.random()*.55,10,8),m);q.position.set((i-3)*.55+(Math.random()-.5)*.4,(Math.random()-.5)*.35,(Math.random()-.5)*.5);q.scale.y=.6;g.add(q)}g.position.set(-8+Math.random()*16,5+Math.random()*2,-2-Math.random()*6);g.userData.speed=.12+Math.random()*.16;world.add(g);clouds.push(g)}
function init3D(){renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x153047,.018);camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.1,120);camera.position.set(0,3.4,11.5);camera.lookAt(0,2,-2);clock=new THREE.Clock();world=new THREE.Group();scene.add(world);hemi=new THREE.HemisphereLight(0x93c7ff,0x15220f,1.2);scene.add(hemi);sunLight=new THREE.DirectionalLight(0xffd28a,3);sunLight.position.set(-8,10,8);sunLight.castShadow=true;sunLight.shadow.mapSize.set(1024,1024);scene.add(sunLight);moonLight=new THREE.DirectionalLight(0x8db8ff,0);moonLight.position.set(5,8,4);scene.add(moonLight);flash=new THREE.PointLight(0xd9ecff,0,45);flash.position.set(0,8,3);scene.add(flash);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(80,80),mat(0x142219,.98));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);pathMaterial=new THREE.MeshStandardMaterial({color:0x343839,roughness:.48,metalness:.12});const path=new THREE.Mesh(new THREE.PlaneGeometry(5,24,6,20),pathMaterial);path.rotation.x=-Math.PI/2;path.position.set(0,.018,-5);path.receiveShadow=true;world.add(path);for(let i=0;i<18;i++){const seam=addBox(world,[4.7,.025,.035],[0,.035,5-i*.65],mat(0x111517));}
 const oceanMat=new THREE.MeshPhysicalMaterial({color:0x0b6281,roughness:.18,metalness:.08,transparent:true,opacity:.9});ocean=new THREE.Mesh(new THREE.PlaneGeometry(80,30,80,30),oceanMat);ocean.rotation.x=-Math.PI/2;ocean.position.set(0,.04,-24);world.add(ocean);makeGate(-2.25);makeGate(2.25);makeTemple();[-6,-5,-4.5,4.5,5,6].forEach((x,i)=>makePalm(x,-1-i%2*3,.72+Math.random()*.35));for(let i=0;i<16;i++)makeCloud();
 sun=new THREE.Mesh(new THREE.SphereGeometry(.65,24,18),new THREE.MeshBasicMaterial({color:0xffe0a0}));scene.add(sun);const sunGlow=new THREE.PointLight(0xffb85a,4,30);sun.add(sunGlow);moon=new THREE.Mesh(new THREE.SphereGeometry(.52,24,18),mat(0xdfe8ef,.95));scene.add(moon);const starPos=new Float32Array(1200);for(let i=0;i<400;i++){starPos[i*3]=(Math.random()-.5)*60;starPos[i*3+1]=4+Math.random()*25;starPos[i*3+2]=-5-Math.random()*45}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(starPos,3));stars=new THREE.Points(sg,new THREE.PointsMaterial({color:0xffffff,size:.055,transparent:true,opacity:.9}));scene.add(stars);
 const rp=new Float32Array(3600);for(let i=0;i<1200;i++){rp[i*3]=(Math.random()-.5)*20;rp[i*3+1]=Math.random()*15;rp[i*3+2]=(Math.random()-.5)*18}const rg=new THREE.BufferGeometry();rg.setAttribute('position',new THREE.BufferAttribute(rp,3));rain=new THREE.Points(rg,new THREE.PointsMaterial({color:0xa9d9ff,size:.035,transparent:true,opacity:.7}));scene.add(rain);rain.visible=false;
 addEventListener('resize',resize);let px=0,py=0;addEventListener('pointermove',e=>{px=(e.clientX/innerWidth-.5);py=(e.clientY/innerHeight-.5)});addEventListener('deviceorientation',e=>{if(e.gamma!=null){px=Math.max(-.5,Math.min(.5,e.gamma/70));py=Math.max(-.5,Math.min(.5,(e.beta-45)/90))}});renderer.setAnimationLoop(()=>animate(px,py));resize();setTimeout(()=>$('#boot').classList.add('hide'),1000)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function weatherMode(){const c=state.weather?.current||{};const code=+c.weather_code||0;return {code,day:c.is_day!==0,cloud:+c.cloud_cover||0,wind:+c.wind_speed_10m||0,raining:(code>=51&&code<=82)||code>=95,storm:code>=95}}
function applyWorld(){if(!state.weather)return;const m=weatherMode(),now=new Date(),h=now.getHours()+now.getMinutes()/60,angle=(h-6)/12*Math.PI;sun.visible=m.day;moon.visible=!m.day;stars.visible=!m.day;sun.position.set(Math.cos(angle)*12,Math.max(-2,Math.sin(angle)*12),-14);moon.position.set(-6,8,-14);hemi.intensity=m.day?(m.storm?.35:m.raining?.58:1.15):.2;sunLight.intensity=m.day?(m.storm?.2:m.raining?.65:2.8):0;moonLight.intensity=m.day?0:.7;scene.background=new THREE.Color(m.day?(m.storm?0x111827:m.raining?0x466477:0x77b6d9):0x020817);scene.fog.color.set(m.day?(m.storm?0x10151c:m.raining?0x49606c:0x87a9b7):0x050b14);scene.fog.density=m.raining?.032:m.cloud>80?.025:.014;rain.visible=state.effects&&m.raining;clouds.forEach(c=>{c.visible=m.cloud>5||m.raining;c.children.forEach(q=>q.material.opacity=.08+m.cloud/100*.42)});pathMaterial.roughness=m.raining?.16:.52;pathMaterial.metalness=m.raining?.42:.08;$('#skyStatus').textContent=m.storm?'Live thunderstorm: dark sky, heavy rain, wet stone and lightning are active.':m.raining?'Live rain: rain particles, wet reflections and cloud cover are active.':!m.day?'Live night: Moon, stars and temple lanterns are active.':m.cloud>65?'Live cloudy sky: cloud density and softer daylight follow current conditions.':'Live daylight: sun position, sky light and palm movement follow local conditions.'}
function animate(px,py){const dt=Math.min(clock.getDelta(),.04),m=weatherMode(),wind=Math.max(1,m.wind);if(state.motion){camera.position.x+=(px*1.1-camera.position.x)*.025;camera.position.y+=(3.4-py*.45-camera.position.y)*.025;camera.lookAt(0,2,-2);palms.forEach((p,i)=>p.rotation.z=Math.sin(performance.now()*.0015+i)*.01*Math.min(wind,30));clouds.forEach(c=>{c.position.x+=dt*c.userData.speed*(.4+wind/8);if(c.position.x>11)c.position.x=-11});const pos=ocean.geometry.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i);pos.setZ(i,Math.sin(performance.now()*.001+x*.35+y*.22)*.08)}pos.needsUpdate=true}
 if(rain.visible){const p=rain.geometry.attributes.position.array;for(let i=0;i<1200;i++){p[i*3+1]-=dt*(9+(m.storm?8:0));p[i*3]-=dt*wind*.045;if(p[i*3+1]<0){p[i*3+1]=15;p[i*3]=(Math.random()-.5)*20}}rain.geometry.attributes.position.needsUpdate=true}
 if(m.storm&&state.effects&&performance.now()>stormNext){flash.intensity=25;$('#lightning').animate([{opacity:0},{opacity:.75},{opacity:0}],{duration:230});stormNext=performance.now()+2300+Math.random()*5000}flash.intensity*=.82;renderer.render(scene,camera)}
async function locate(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve();navigator.geolocation.getCurrentPosition(p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;state.place='Current location';resolve()},()=>resolve(),{enableHighAccuracy:false,timeout:7000,maximumAge:600000})})}
async function loadWeather(){const btn=$('#refreshBtn');btn.disabled=true;$('#dataState').textContent='CONNECTING';try{const u=new URL('https://api.open-meteo.com/v1/forecast');u.search=new URLSearchParams({latitude:state.lat,longitude:state.lon,current:'temperature_2m,apparent_temperature,relative_humidity_2m,is_day,precipitation,rain,weather_code,cloud_cover,wind_speed_10m',hourly:'temperature_2m,precipitation_probability,weather_code',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max',timezone:'auto',forecast_days:'8'});const r=await fetch(u);if(!r.ok)throw new Error('weather '+r.status);state.weather=await r.json();renderWeather();applyWorld();$('.status').className='status glass live';$('#dataState').textContent='LIVE OPEN-METEO';$('#updated').textContent='Updated '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});localStorage.setItem('skygates-v027-last',JSON.stringify({at:Date.now(),place:state.place,data:state.weather}))}catch(e){const cached=localStorage.getItem('skygates-v027-last');if(cached){const x=JSON.parse(cached);state.weather=x.data;state.place=x.place;renderWeather();applyWorld();$('#dataState').textContent='CACHED WEATHER';$('#updated').textContent='Saved '+new Date(x.at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}else{$('#dataState').textContent='UPDATE FAILED';$('#condition').textContent='Live weather unavailable'}$('.status').className='status glass error'}finally{btn.disabled=false}}
function renderWeather(){const d=state.weather,c=d.current,h=d.hourly,dy=d.daily,unit=d.current_units.temperature_2m||'°C';$('#place').textContent=state.place;$('#temperature').textContent=Math.round(c.temperature_2m)+unit.replace('°','°');$('#condition').textContent=codes[c.weather_code]||'Current conditions';$('#feels').textContent='Feels like '+Math.round(c.apparent_temperature)+unit;$('#highLow').textContent='↑ '+Math.round(dy.temperature_2m_max[0])+'°  ↓ '+Math.round(dy.temperature_2m_min[0])+'°';$('#weatherIcon').textContent=icons(c.weather_code);$('#rain').textContent=Math.round(h.precipitation_probability?.[0]??0)+'%';$('#wind').textContent=Math.round(c.wind_speed_10m)+' '+(d.current_units.wind_speed_10m||'km/h');$('#humidity').textContent=Math.round(c.relative_humidity_2m)+'%';const start=Math.max(0,h.time.findIndex(t=>new Date(t)>=new Date())-1);const cards=h.time.slice(start,start+24).map((t,i)=>`<div class="hour-card"><span>${fmtTime(t)}</span><div>${icons(h.weather_code[start+i])}</div><b>${Math.round(h.temperature_2m[start+i])}°</b><span>${Math.round(h.precipitation_probability[start+i]||0)}% rain</span></div>`).join('');$('#hourStrip').innerHTML=cards;$('#hourGrid').innerHTML=cards;$('#weekGrid').innerHTML=dy.time.slice(0,7).map((t,i)=>`<div class="week-row"><b>${fmtDay(t)}</b><span>${icons(dy.weather_code[i])}</span><span>${Math.round(dy.temperature_2m_max[i])}° / ${Math.round(dy.temperature_2m_min[i])}°</span><span>${Math.round(dy.precipitation_probability_max[i]||0)}%</span></div>`).join('');const mp=moonInfo(new Date());$('#moonPhase').textContent=mp.name;$('#moonLight').textContent=mp.light+'%';$('#stargazing').textContent=(c.cloud_cover<35&&!(weatherMode().raining))?'Good':'Limited';}
function moonInfo(date){const syn=29.530588853,known=Date.UTC(2000,0,6,18,14),age=((date-known)/86400000%syn+syn)%syn,phase=age/syn,light=Math.round((1-Math.cos(phase*2*Math.PI))/2*100);let name=phase<.03||phase>.97?'New Moon':phase<.22?'Waxing Crescent':phase<.28?'First Quarter':phase<.47?'Waxing Gibbous':phase<.53?'Full Moon':phase<.72?'Waning Gibbous':phase<.78?'Last Quarter':'Waning Crescent';return{name,light}}
function clockTick(){$('#localTime').textContent='Local time '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});requestAnimationFrame(()=>setTimeout(clockTick,30000))}
$$('.section-tabs button').forEach(b=>b.onclick=()=>{$$('.section-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.page))});$('#refreshBtn').onclick=loadWeather;$('#locationBtn').onclick=async()=>{await locate();loadWeather()};$('#motionToggle').onchange=e=>state.motion=e.target.checked;$('#effectsToggle').onchange=e=>{state.effects=e.target.checked;applyWorld()};$('#qualityBtn').onclick=e=>{state.quality=state.quality==='auto'?'battery':state.quality==='battery'?'high':'auto';e.target.textContent='Quality: '+state.quality[0].toUpperCase()+state.quality.slice(1);renderer.setPixelRatio(state.quality==='battery'?1:state.quality==='high'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,1.6))};
init3D();clockTick();await locate();await loadWeather();